[package]
name = "pendb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.135", features = ["derive"]}
serde-xml-rs = "0.5.1"
# serde_json = "1.0.78"
walkdir = "2.3.2"